# Generated by Django 6.0.6 on 2026-07-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_point_address_alter_point_mail_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='app.point')),
            ],
        ),
    ]
